/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BlogBrief: typeof import('./src/components/blogBrief.vue')['default']
    Button: typeof import('./src/components/button.vue')['default']
    CommonLink: typeof import('./src/components/commonLink.vue')['default']
    FeedbackForm: typeof import('./src/components/FeedbackForm.vue')['default']
    Footer: typeof import('./src/components/footer.vue')['default']
    Header: typeof import('./src/components/header.vue')['default']
    Pagination: typeof import('./src/components/pagination.vue')['default']
    Tag: typeof import('./src/components/tag.vue')['default']
    ToolBar: typeof import('./src/components/toolBar.vue')['default']
  }
}
